expr=require('express')
app=expr()
path=require('path')
sp=path.join(__dirname,'../public')
app.use(expr.static(sp))
app.get('/',(req,res)=>{
    res.sendFile(sp+'/index.html')
})
app.listen(3001)